# Generated by Django 5.1.3 on 2024-11-28 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BookingInfo', '0001_initial'),
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_type', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'PAYMENT SOURCE',
                'verbose_name_plural': 'PAYMENT SOURCE',
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_no_or_cust_id', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Expired', 'Expired'), ('Declined', 'Declined'), ('Failed', 'Failed')], default='Pending', max_length=50)),
                ('payment_gateway', models.CharField(blank=True, max_length=250, null=True)),
                ('gateway_order_id', models.CharField(blank=True, max_length=250, null=True)),
                ('gateway_charges', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('gateway_session_id', models.CharField(blank=True, max_length=250, null=True)),
                ('gateway_message', models.CharField(blank=True, max_length=300, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=300, null=True)),
                ('payment_parm', models.CharField(blank=True, max_length=300, null=True)),
                ('indent_vpa_uri', models.JSONField(blank=True, null=True)),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('loyalti_transaction_type', models.CharField(blank=True, max_length=250, null=True)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('special_coupon', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('e_point', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('i_point', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cgst_sgst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('net_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('crmId', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_number', models.CharField(blank=True, max_length=255, null=True)),
                ('billNumberOrInvoiceNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('transactionReferenceNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('requested_employee_id', models.CharField(blank=True, max_length=255, null=True)),
                ('requested_employee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('requested_employee_mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('requested_employee_location', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('channel', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('dont_show', models.BooleanField(default=False)),
                ('callBackUrl', models.URLField(blank=True, max_length=500, null=True)),
                ('payu_webhook_call', models.BooleanField(default=False)),
                ('internal_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_crm', to='CustomUser.profile')),
            ],
            options={
                'verbose_name': 'PAYMENT REQUEST',
                'verbose_name_plural': 'PAYMENT REQUEST',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference_no', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_status', models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Expired', 'Expired'), ('Failed', 'Failed'), ('Error', 'Error')], default='Pending', max_length=50)),
                ('mode_of_payment', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('transaction_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('booking_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_transaction', to='BookingInfo.appbooking')),
                ('crm_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_profile', to='CustomUser.profile')),
                ('payment_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_transaction', to='CollectionInfo.paymentrequest')),
            ],
            options={
                'verbose_name': 'PAYMENT TRANSACTION',
                'verbose_name_plural': 'PAYMENT TRANSACTION',
            },
        ),
    ]
