# Generated by Django 5.1.3 on 2024-11-28 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProductData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(blank=True, max_length=250, null=True)),
                ('version_description', models.CharField(blank=True, max_length=250, null=True)),
                ('version_number', models.CharField(blank=True, max_length=250, null=True)),
                ('version_notes', models.CharField(blank=True, max_length=250, null=True)),
                ('version_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('version_status', models.CharField(blank=True, max_length=250, null=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'APP VERSIONS',
                'verbose_name_plural': 'APP VERSIONS',
            },
        ),
        migrations.CreateModel(
            name='AwardsAndAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('classname', models.CharField(blank=True, max_length=250, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'AWARD AND ACHIEVEMENT',
                'verbose_name_plural': 'AWARDS AND ACHIEVEMENTS',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'OUTLET CITY',
                'verbose_name_plural': 'OUTLET CITY',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('customer_review', models.TextField()),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('thumbnail_img_link', models.URLField(blank=True, max_length=500, null=True)),
                ('vehicle_review_link', models.URLField(blank=True, max_length=500, null=True)),
                ('platform', models.CharField(choices=[('Native', 'Native'), ('Web', 'Web'), ('Other', 'Other')], default='Other', max_length=250)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'REVIEWS',
                'verbose_name_plural': 'REVIEWS',
            },
        ),
        migrations.CreateModel(
            name='RTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.CharField(blank=True, max_length=255, null=True)),
                ('is_popular', models.CharField(blank=True, max_length=255, null=True)),
                ('rto_code', models.CharField(blank=True, max_length=255, null=True)),
                ('rto_id', models.CharField(blank=True, max_length=255, null=True)),
                ('rto_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charges_term', models.TextField(blank=True, default=None, max_length=1000, null=True)),
                ('charges_more_term', models.TextField(blank=True, default=None, max_length=1000, null=True)),
                ('declarations_term', models.TextField(blank=True, default=None, max_length=1000, null=True)),
                ('booking_advance_note', models.TextField(blank=True, default=None, max_length=1000, null=True)),
                ('loyalty_terms', models.TextField(blank=True, default=None, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'TERMS AND CONDITIONS',
                'verbose_name_plural': 'TERMS AND CONDITIONS',
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Showroom', 'Showroom'), ('Truevalue', 'Truevalue'), ('Workshop', 'Workshop'), ('Commercial', 'Commercial')], default='Showroom', max_length=50)),
                ('sap_outlet_name', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='ProductData.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='CompanyData.city')),
            ],
            options={
                'verbose_name': 'OUTLET LOCATION',
                'verbose_name_plural': 'OUTLET LOCATION',
            },
        ),
        migrations.CreateModel(
            name='TrueValueLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('google_map_link', models.URLField(blank=True, max_length=500, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tv_loc', to='CompanyData.city')),
            ],
            options={
                'verbose_name': 'TRUEVALUE LOCATION',
                'verbose_name_plural': 'TRUEVALUE LOCATIONS',
            },
        ),
    ]
