# Generated by Django 5.1.3 on 2024-11-28 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode_name', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], default='Active', max_length=50)),
            ],
            options={
                'verbose_name': 'PAYMENT MODE',
                'verbose_name_plural': 'PAYMENT MODE',
            },
        ),
        migrations.CreateModel(
            name='PaymentModes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMode', models.CharField(blank=True, choices=[('PHONEPAY', 'PHONEPAY'), ('GOOGLEPAY', 'GOOGLEPAY'), ('CRED', 'CRED'), ('PAYTM', 'PAYTM'), ('UPI', 'UPI')], max_length=255, null=True)),
                ('aggregatorName', models.CharField(blank=True, max_length=255, null=True)),
                ('aggregatorext', models.CharField(blank=True, max_length=255, null=True)),
                ('aggregatorIcon', models.ImageField(blank=True, null=True, upload_to='media/paymentMode/')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'AVAILABLE MODES',
                'verbose_name_plural': 'AVAILABLE MODES',
            },
        ),
        migrations.CreateModel(
            name='PayuBanksInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(blank=True, max_length=250, null=True)),
                ('bankCode', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.CharField(blank=True, max_length=250, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'PAYU BANK INFO',
                'verbose_name_plural': 'PAYU BANK INFO',
            },
        ),
        migrations.CreateModel(
            name='UserOwnedModes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeParams', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=255, null=True)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaymentMode.paymentmodes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomUser.profile')),
            ],
            options={
                'verbose_name': 'USER OWNED',
                'verbose_name_plural': 'USER OWNED',
            },
        ),
    ]
